---
_meta:
  type: "internalusers"
  config_version: 2
admin:
  hash: "$2y$12$AvABzStngEFC5N4Smzjj6uceELmszJf8qL3B7L30WSQs9NS4Q1Eeq"
  reserved: true
  backend_roles:
  - "admin"
  description: "Admin user"
dashboards:
  hash: "$2y$12$AvABzStngEFC5N4Smzjj6uceELmszJf8qL3B7L30WSQs9NS4Q1Eeq"
  backend_roles:
  - "admin"
  - "dashboards"
  opendistro_security_roles:
  - "dashboards"
  description: "User that Dashboard will access OpenSearch"
kibanaserver:
  hash: "$2y$12$AvABzStngEFC5N4Smzjj6uceELmszJf8qL3B7L30WSQs9NS4Q1Eeq"
  reserved: true
  description: "Demo kibanaserver user"